import {HistoricalAdapter} from './historical-adapter.js';
import {rankStocks, explainRanking} from './scoring.js';
const adapter=new HistoricalAdapter();
const colors=['#63e2c1','#7fa8ff','#f2b84b','#ff7d86','#bd8cff'];
const state={snapshot:null,selected:new Set(['AAPL','MSFT','NVDA']),weights:{momentum:.4,volatility:.3,sentiment:.3},ranked:[],returns:false};
const $=id=>document.getElementById(id), pct=n=>`${n>=0?'+':''}${n.toFixed(1)}%`;
async function init(){
  const snapshots=await adapter.listSnapshots();
  $('dateSelect').innerHTML=snapshots.map(s=>`<option value="${s.date}">${s.date} · ${s.event}</option>`).join('');
  renderWeights(); await loadSnapshot(snapshots[0].date);
  $('dateSelect').onchange=e=>loadSnapshot(e.target.value); $('runBtn').onclick=run; $('toggleReturns').onclick=toggleReturns;
  document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
}
async function loadSnapshot(date){state.snapshot=await adapter.getSnapshot(date);state.ranked=[];state.returns=false;$('eventCard').innerHTML=`<b>${state.snapshot.event}</b>${state.snapshot.description}`;renderTickers();resetResults();}
function renderTickers(){const valid=new Set(state.snapshot.stocks.map(s=>s.ticker));state.selected=new Set([...state.selected].filter(t=>valid.has(t)));if(state.selected.size<2)state.snapshot.stocks.slice(0,3).forEach(s=>state.selected.add(s.ticker));$('tickerGrid').innerHTML=state.snapshot.stocks.map(s=>`<button class="ticker ${state.selected.has(s.ticker)?'selected':''}" data-t="${s.ticker}">${s.ticker}</button>`).join('');document.querySelectorAll('.ticker').forEach(b=>b.onclick=()=>{const t=b.dataset.t;if(state.selected.has(t)&&state.selected.size>2)state.selected.delete(t);else if(!state.selected.has(t)&&state.selected.size<5)state.selected.add(t);state.ranked=[];state.returns=false;renderTickers();resetResults();});}
function renderWeights(){const labels={momentum:'Price momentum',volatility:'Lower volatility',sentiment:'News sentiment'};$('weightControls').innerHTML=Object.entries(state.weights).map(([k,v])=>`<div class="weight"><div class="weight-line"><span>${labels[k]}</span><span id="${k}Value">${Math.round(v*100)}%</span></div><input aria-label="${labels[k]} weight" data-w="${k}" type="range" min="5" max="80" value="${Math.round(v*100)}"></div>`).join('');document.querySelectorAll('[data-w]').forEach(r=>r.oninput=()=>adjustWeight(r.dataset.w,+r.value));}
function adjustWeight(key,value){const others=Object.keys(state.weights).filter(k=>k!==key),remaining=100-value,current=others.reduce((a,k)=>a+state.weights[k],0);state.weights[key]=value/100;others.forEach(k=>state.weights[k]=(remaining*(state.weights[k]/current))/100);Object.entries(state.weights).forEach(([k,v])=>{const el=$(k+'Value');if(el)el.textContent=Math.round(v*100)+'%';const slider=document.querySelector(`[data-w="${k}"]`);if(k!==key)slider.value=Math.round(v*100);});state.ranked=[];state.returns=false;resetResults();}
function resetResults(){$('analysisTitle').textContent='Historical ranking';$('analysisMeta').textContent=`Research date: ${state.snapshot.date}`;$('rankingTable').className='empty';$('rankingTable').innerHTML='<div class="empty-icon">↗</div><h3>No ranking yet</h3><p>Configure the analysis on the left and run the model.</p>';$('explanation').className='empty small';$('explanation').innerHTML='<p>The explanation will appear after a ranking is calculated.</p>';$('chart').className='empty small';$('chart').innerHTML='<p>Select stocks to draw their historical path.</p>';$('evidence').className='empty small';$('evidence').innerHTML='<p>Source cards will appear here.</p>';$('statusBanner').innerHTML='<span>Ready</span><p>Configure the illustrative comparison, then run the ranking.</p>';$('toggleReturns').textContent='Reveal later returns';$('toggleReturns').disabled=true;$('kpiStocks').textContent='—';$('kpiWinner').textContent='—';$('kpiReturn').textContent='Hidden';}
function run(){const stocks=state.snapshot.stocks.filter(s=>state.selected.has(s.ticker));if(stocks.length<2)return;state.ranked=rankStocks(stocks,state.weights);state.returns=false;$('analysisTitle').textContent=`${state.ranked.map(s=>s.ticker).join(' vs ')} ranking`;$('analysisMeta').textContent=`Research date: ${state.snapshot.date} · ${state.snapshot.event}`;$('statusBanner').innerHTML='<span>Calculated</span><p>Ranking generated from illustrative snapshot factors. Later returns remain hidden.</p>';$('kpiStocks').textContent=state.ranked.length;$('kpiWinner').textContent=state.ranked[0].ticker;$('kpiReturn').textContent='Hidden';$('toggleReturns').disabled=false;$('toggleReturns').textContent='Reveal later returns';renderRanking();renderExplanation();renderChart();renderEvidence();}
function renderRanking(){$('rankingTable').className='';$('rankingTable').innerHTML='<div class="ranking-row head"><span>Rank</span><span>Company</span><span>Model score</span><span>Momentum</span><span>Later return</span></div>'+state.ranked.map((s,i)=>`<div class="ranking-row"><span class="rank">#${i+1}</span><span class="company"><b>${s.ticker}</b><small>${s.name}</small></span><span><div class="scorebar"><i style="width:${s.score}%"></i></div><span class="components">${s.score.toFixed(1)} · M ${(s.components.momentum*100).toFixed(0)} / V ${(s.components.volatility*100).toFixed(0)} / N ${(s.components.sentiment*100).toFixed(0)}</span></span><span>${pct(s.momentum)}</span><span class="${state.returns?'future-return':'hidden-return'}">${state.returns?pct(s.futureReturn):'••••'}</span></div>`).join('');}
function renderExplanation(){$('explanation').className='explain-list';$('explanation').innerHTML=explainRanking(state.ranked).map(x=>`<div class="explain-item"><b>${x.title}</b><p>${x.text}</p></div>`).join('');}
function renderEvidence(){$('evidence').className='evidence-grid';$('evidence').innerHTML=state.ranked.map(s=>`<article class="evidence-card"><div class="top"><b>${s.ticker}</b><span>${s.news.date}</span></div><h3>${s.news.title}</h3><p>${s.news.summary}</p><a href="${s.news.url}" target="_blank" rel="noreferrer">Open ${s.news.source} ↗</a></article>`).join('');}
function renderChart(){if(!state.returns){$('chart').className='empty small';$('chart').textContent='Later paths are hidden until you reveal later returns.';return;}const W=520,H=180,pad=18,series=state.ranked.map(s=>s.path),all=series.flat(),lo=Math.min(...all)-2,hi=Math.max(...all)+2,xy=(v,i,n)=>[pad+i*(W-2*pad)/(n-1),H-pad-(v-lo)*(H-2*pad)/(hi-lo)];let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Indexed price paths">${[0,1,2,3].map(i=>`<line class="grid-line" x1="${pad}" x2="${W-pad}" y1="${pad+i*(H-2*pad)/3}" y2="${pad+i*(H-2*pad)/3}"/>`).join('')}`;series.forEach((a,j)=>{svg+=`<polyline class="series" stroke="${colors[j]}" points="${a.map((v,i)=>xy(v,i,a.length).join(',')).join(' ')}"/>`});svg+='</svg>';$('chart').className='chart-wrap';$('chart').innerHTML=svg+`<div class="chart-key">${state.ranked.map((s,i)=>`<span><i style="background:${colors[i]}"></i>${s.ticker}</span>`).join('')}</div>`;}
function toggleReturns(){state.returns=!state.returns;$('statusBanner').innerHTML='<span>Calculated</span><p>Ranking generated from illustrative snapshot factors. '+(state.returns?'Later outcomes are now visible for comparison.':'Later returns remain hidden.')+'</p>';$('toggleReturns').textContent=state.returns?'Hide later returns':'Reveal later returns';const best=state.ranked.reduce((a,b)=>a.futureReturn>b.futureReturn?a:b);$('kpiReturn').textContent=state.returns?`${best.ticker} ${pct(best.futureReturn)}`:'Hidden';renderRanking();renderChart();}
function switchView(view){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('labView').classList.toggle('active',view==='lab');$('methodView').classList.toggle('active',view==='method');}
init().catch(e=>{$('statusBanner').innerHTML=`<span>Error</span><p>${e.message}</p>`});
